name: Build, Analyze, Scan, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: build
    runs-on: [self-hosted]
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Building code and analyze with SonarQube
        uses: actions/checkout@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: dependencies install
        run: npm install
      - name: trivy scan
        run: trivy fs . > trivy-report.txt
      - name: docker build push
        run: |
          docker build -t zomato .
          docker tag zomato manlineroot12/zomato:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push manlineroot12/zomato:latest
        env:
          DOCKER_CLI_ACL: 1
  deploy:
    name: deploy app to docker
    needs: build-analyze-scan
    runs-on: [self-hosted]
    steps:
      - name: docker pull
        run: docker pull manlineroot12/zomato:latest
      - name: Image scan
        run: trivy image manlineroot12/zomato:latest > image-trivy-scan.txt
      - name: run docker container
        run: docker run -itd -p 3000:3000 --name zomato manlineroot12/zomato:latest
